[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "requests>=2.32.3",
    "scipy>=1.15.2",
]
